{{
    config(
        unique_key='listing_id',
        materialized='view'
    )
}}

with

source  as (

    select * from {{source('raw','listings')}}

),

renamed as (
    SELECT
    listing_id,
    SCRAPED_DATE::date as SCRAPED_DATE,
    HOST_ID,
    CASE 
    WHEN HOST_NAME = 'Na' THEN 'unknown' 
    WHEN HOST_NAME = 'NaN' Then 'unknown' 
    ELSE HOST_NAME
    END AS HOST_NAME,
    CASE WHEN HOST_SINCE = 'NaN' THEN '1900-01-01'::date ELSE to_date(HOST_SINCE, 'DD/MM/YYYY') END AS HOST_SINCE,
    CASE WHEN HOST_IS_SUPERHOST = 'NaN' THEN 'false'::boolean ELSE HOST_IS_SUPERHOST::boolean END AS HOST_IS_SUPERHOST,
    CASE WHEN HOST_NEIGHBOURHOOD = 'NaN' THEN 'unknown' ELSE HOST_NEIGHBOURHOOD END AS HOST_NEIGHBOURHOOD,
    LISTING_NEIGHBOURHOOD,
    PROPERTY_TYPE,
    ROOM_TYPE,
    ACCOMMODATES,
    PRICE::FLOAT as PRICE,
    HAS_AVAILABILITY::boolean,
    AVAILABILITY_30,
    NUMBER_OF_REVIEWS,
    CASE WHEN REVIEW_SCORES_RATING = 'NaN' THEN 0 ELSE REVIEW_SCORES_RATING END AS REVIEW_SCORES_RATING, 
    CASE WHEN REVIEW_SCORES_ACCURACY = 'NaN' THEN 0 ELSE REVIEW_SCORES_ACCURACY END AS REVIEW_SCORES_ACCURACY, 
    CASE WHEN REVIEW_SCORES_CLEANLINESS = 'NaN' THEN 0 ELSE REVIEW_SCORES_CLEANLINESS END AS REVIEW_SCORES_CLEANLINESS, 
    CASE WHEN REVIEW_SCORES_CHECKIN = 'NaN' THEN 0 ELSE REVIEW_SCORES_CHECKIN END AS REVIEW_SCORES_CHECKIN, 
    CASE WHEN REVIEW_SCORES_COMMUNICATION = 'NaN' THEN 0 ELSE REVIEW_SCORES_COMMUNICATION END AS REVIEW_SCORES_COMMUNICATION, 
    CASE WHEN REVIEW_SCORES_VALUE = 'NaN' THEN 0 ELSE REVIEW_SCORES_VALUE END AS REVIEW_SCORES_VALUE
    FROM source
)

select * from renamed